name: Matrix Demo
on: push
jobs:
  build:
    strategy:
      matrix:
        node-version: [12, 14, 16]
        operating-system: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: Get Code
        usees: actions/checkout@v7
      - name: Instal NodeJs
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-verion }}
      - name: Install Deps
        run: npm ci
      - name: Build project
        run: npm run build
